name: Codecov

on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Coverage
        run: |
          pip install -r requirements/requirements_test.txt
          pip install -e .
      - name: Execute coverage
        run: |
          coverage run runtests.py
          codecov -n codecov-umbrella -v -t ${{ secrets.CODECOV_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)