name: Django CI

on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        django:
        - ">=1.11,<=2"
        - ">=2.0,<=2.1"
        - ">=2.1,<=2.2"
        - ">=2.2,<=3"
        - ">=3.0,<=3.1"
        - ">=3.1,<=3.2"
        - ">=3.2,<=3.3"
        exclude:
        - python-version: 3.5
          django: ">=3.0,<=3.1"
        - python-version: 3.5
          django: ">=3.1,<=3.2"
        - python-version: 3.5
          django: ">=3.2,<=3.3"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install "Django${{ matrix.django }}"
        pip install -e .
    - name: Run tests
      run: python runtests.py
